
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOBLE_BARRA = 10;
  public static final int PR_INT = 11;
  public static final int PR_FOR = 22;
  public static final int ENTERO = 2;
  public static final int DIFERENTE = 34;
  public static final int RESTA = 26;
  public static final int PR_IF = 17;
  public static final int PARENTESIS_ABIERTO = 3;
  public static final int PR_WHILE = 23;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int IGUAL = 31;
  public static final int CARACTER = 8;
  public static final int OR = 36;
  public static final int PR_BRAKE = 20;
  public static final int PR_SWITCH = 18;
  public static final int SUMA = 25;
  public static final int PUNTO_COMA = 6;
  public static final int EOF = 0;
  public static final int COMILLAS = 5;
  public static final int error = 1;
  public static final int MENOR = 30;
  public static final int PR_STRING = 15;
  public static final int PR_CHAR = 13;
  public static final int MAYOR = 29;
  public static final int PR_CASE = 19;
  public static final int PR_DEFAULT = 21;
  public static final int PR_DO = 24;
  public static final int MAYOR_IGUAL = 33;
  public static final int PARENTESIS_CERRADO = 4;
  public static final int PR_BOOL = 14;
  public static final int MENOR_IGUAL = 32;
  public static final int SALTO = 9;
  public static final int DIVISION = 28;
  public static final int PR_DOUBLE = 12;
  public static final int PR_CONSOLE = 7;
  public static final int PR_MAIN = 16;
  public static final int MULTIPLICACION = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMILLAS",
  "PUNTO_COMA",
  "PR_CONSOLE",
  "CARACTER",
  "SALTO",
  "DOBLE_BARRA",
  "PR_INT",
  "PR_DOUBLE",
  "PR_CHAR",
  "PR_BOOL",
  "PR_STRING",
  "PR_MAIN",
  "PR_IF",
  "PR_SWITCH",
  "PR_CASE",
  "PR_BRAKE",
  "PR_DEFAULT",
  "PR_FOR",
  "PR_WHILE",
  "PR_DO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT"
  };
}

